import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

const RootLayout = ({ children }: Props) => (
  <html
    lang="en"
    className="min-h-screen bg-gradient-to-b from-white via-slate-200 to-slate-200"
  >
    <body className={dmSans.className}>{children}</body>
  </html>
);

export default RootLayout;
